project:
  type: book
  output-dir: docs

book:
  title: "Statistical Machine Learning and Data Mining"
  author: "Kyungsub Lee"
  chapters:
    - index.qmd
    - 01. Introduction.ipynb
    - 02. Model_evaluation.ipynb
    - 03. Linear regression.ipynb
    - 04. Classification - Logistic Regression.ipynb
    - 05. Classficatrion - LDA.ipynb
    - 06. Resampling.ipynb
    - 07. Regularization.ipynb
    - 08. Tree.ipynb
    - 09. Prunning tree.ipynb
    - 10. Bagging.ipynb
    - 11. Random forest.ipynb
    - 12. Boosting.ipynb
    - 13. XGBoost.ipynb
    - 14. LightGBM.ipynb
    - 15. Unsupervised.ipynb
    - 16. SVM.ipynb
    
execute:
  freeze: auto
  error: false
  
  
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  #pdf:
    #documentclass: scrbook
